### ISSUE TITLE
can't scroll content of native/custom/samples palette

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerLabs/wizzywid#13]
![screen shot 2017-08-03 at 9 51 56 am](https://user-images.githubusercontent.com/6173664/28933284-69b8d62e-7831-11e7-9f25-bec35c8a9709.png)

**Comment by dmitriid** [comment]
Still can't scroll content in the palette on Safari 10.1.2 (12603.3.8), MacOS 10.12.6

**Comment by metasean** [comment]
Also can't scroll content in the palette on Firefox Nightly 58.0a1 (2017-10-06), MacOS 10.12.6
