### ISSUE TITLE
Support Polymer 3 without putting me into a funk

### ISSUE THREAD

**Issue by bahrus** [PolymerLabs/wizzywid#21]
This looks great, love the name!  Feel free to close this issue  right away, this is just my rambling, half-baked feedback / thoughts.

It causes me pain just thinking about what this gem will look like when migrating it to Polymer 3.  Okay, I'm sure I'll be proven wrong, but... I wonder if it makes sense to:

- Separate the tool into "crafting" components vs "assembling" _pages/fragments_ which can reference the components.  
  - The craft part would help with writing a custom element using JavaScript / template literals (sigh).
  - As for assembling, introduce into Polymer a Polymer-supported custom element that does client-side includes - something like my favorite angular 1 directive: "ng-include," as a custom element that the polymer IDE and other polymer tools would know about.  It just retrieves a snippet of html and pastes it inside the custom element.  And maybe caches it.  And handles script tags. And maybe uses HTML templates somehow for better performance.   And supports lazy loading.  And during build, optionally supports embedding (in cases where the HTML was split only to make files easier to manage, not for reuse).  This would also be useful for applications that use some server-side generation, like asp.net mvc or [J2EE MVC](https://zeroturnaround.com/rebellabs/modern-web-apps-with-html5-web-components-polymer-and-java-ee-mvc-1-0-by-kito-mann/).  I think.

   - Add support for assembling html snippets together in wizzywid, to build old-fashioned HTML declarative designs.

**Comment by notwaldorf** [comment]
I don't think this should look any different when migrating to Polymer 3? There are no core changes in the core library itself, the only thing that is changing is moving from an HTML import to an es6 module -- so all of the code will stay the same, but in a .js file, rather than a .html file.

/cc @justinfagnani in case he can explain this better

**Comment by bahrus** [comment]
True, assuming the html syntax highlighting for template literals is supported, which I'm sure it can be.  Right now, the HTML isn't editable, so hard to tell if it will already.  And it doesn't feel *right* to me to be editing a JavaScript file using a wyziwi(d|g) tool, somehow, but that's just me.  But it could still help quickly prototype things, so no need to let that bias  get in the way, I suppose.

I'm of the current opinion that with the decision to remove importHREF (for now), and assuming all the findings from Addy Osmani are correct that JavaScript is expensive, compared to markup, then the focus of web components ought to be on reusable components -i.e. "crafting."  There needs to be a slight variation of component -- call it module / page / view?  where the "assembling" takes place in HTML. And served as HTML, not JavaScript.   Pages that are unique and unlikely to ever be used again.  Particularly for heavy content sites.  

But I await more guidance from you and the rest of the Polymer team how best to balance performance / maintainability / integration with other tools.  It's a difficult balancing act, I imagine.

If any such suggestion like what I hope to see emerges from Polymer, then I would hope this tool would help creating such a [yet unnamed] thing.

Anyway, thanks for the tool, looks great.

**Comment by justinfagnani** [comment]
@notwaldorf is correct in her assessment. I'll only add that we're going to be exploring ideas for writing templates in HTML files, probably via some build step, for those who want that. It's still very early in 3.0 days, so please be patient.

**Comment by ArvindAkula** [comment]
Can you point me any sample example using Ploymer3+Spring Boot

**Comment by boluwalade** [comment]
Does anyone have an example,e of how to use this tool with polymer 3?

**Comment by jogibear9988** [comment]
Maybe try my fork at https://github.com/node-projects/web-component-designer
It will be a bare webcomponent without need of any Lib.

But it's not yet finished. We got a little stuck cause of other projects, but we will work on this with more power in the next months...
