### ISSUE TITLE
Remove the bower_components folder

### ISSUE THREAD

**Issue by manolo** [PolymerLabs/wizzywid#23]
Is there any strong reason for maintaining the bower stuff in the git history? IMO almost people checking out this repo are familiar with the process of installing those.

**Comment by syu93** [comment]
I think the reason is because it's a builder those, dependencies are absolutely necessary to the aim of the whole project, so it does make sense to have theme committed here. So the builder can work out of the box without any possible resolving issues.

But like you, I was surprised the first time

**Comment by SilverPaladin** [comment]
I have created a pull request for this: https://github.com/PolymerLabs/wizzywid/pull/24

**Comment by notwaldorf** [comment]
Yup, the reason is that I'm serving the demo off the master branch, and not
gh-pages. I'll add the gh-pages deploying script I used in indie-catalog,
and then we can delete the bower_components folder

**Comment by notwaldorf** [comment]
Fixed in 9bcd98c
